# Generated by Django 3.2.8 on 2021-10-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
