# Generated by Django 3.2.8 on 2021-10-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapp', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=250)),
                ('im', models.ImageField(upload_to='pics')),
                ('des', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
